project_id = "rwsclxynczuimgnjmicp"

[functions.create-user]
verify_jwt = true

[functions.create-initial-user]
verify_jwt = false

[functions.login-with-username]
verify_jwt = false

[functions.signup-with-username]
verify_jwt = false

[functions.simple-login]
verify_jwt = false

[functions.simple-signup]
verify_jwt = false

[functions.external-sync]
verify_jwt = true

[functions.update-user]
verify_jwt = true
