project_id = "rwsclxynczuimgnjmicp"

[functions.create-user]
verify_jwt = true

[functions.create-initial-user]
verify_jwt = false

[functions.login-with-username]
verify_jwt = false

[functions.signup-with-username]
verify_jwt = false
